version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    labels:
      - "no changelog"

updates:
  - package-ecosystem: maven
    directories:
      - "/"
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies
    cooldown:
      default-days: 7
    ignore:
    - dependency-name:  com.sap.cds:*
      versions:
      - ">=4"

  - package-ecosystem: npm
    directories:
      - "/"
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies
    cooldown:
      default-days: 7
