
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
cds:
  data-source.auto-config.enabled: false
n8n:
  webhooks:
    orderCreated:
      url: http://localhost:5678/webhook/order-created
      apiKey: ${N8N_API_KEY:}
    bookCreated:
      url: http://localhost:5678/webhook/book-created
      apiKey: ${N8N_API_KEY:}
    bookDeleted:
      url: http://localhost:5678/webhook/book-deleted
      apiKey: ${N8N_API_KEY:}
