name: Deploy to Maven Central

on:
  release:
    types: [ "released" ]

jobs:
  release:
    uses: cap-java/.github/.github/workflows/release.yml@b5eb1ad6341e9fd1d681c42f3b36c4b750a7dac2 #main
    with:
      blackduck-project-name: com.sap.cds.cds.feature.n8n
      blackduck-included-modules: cds-feature-n8n
    secrets: inherit
